version: "3"

###############################
#       TEST ENVIRONMENT      #
###############################

services:
  # PostgreSQL Database
  test-database:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test-db
    networks:
      - backend_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  backend_network:
    driver: bridge
